language: ruby
rvm:
- 2.3.1
script: bundle exec rspec
deploy:
  provider: heroku
  app: citibike-slackbot
  api_key:
    secure: K72MPIpOpL41R5fBlXWewYL9d5Bwnn0YRMsCvmGTm3TnAH0O+4XzBmMcx2xr1JFDWAOR6OKUDZ516lIyWro+ZRQqGrmZyz6Rap1arxop4Zy4Ysad1Z5Z6W4jQXT7F1RzVaR96sdFzJf0qnIaj4bSakRFc/9UpH+N45NyV/UdUq0ars1notZGleCzhHOxrApqJRyc02G0g6ai+Fp92TOUtogK+CqB1BvUvP4MACKvQL5AFsjCYfyww/OSGD3fsuNYcF5nKi5RHQ++iqgcBHAc1T351QKIcnkyzE9HnmpSbMfTtth1x4d6FDLfVnnwUMu/tJHsyCWSetNcQd7SOLSG52+UqNgPNIZRKkju5GdB56tfzp9SgrAxyyKvC1zHE+DbHSfCArl/L+QzAor+wgOoPkbCY4FueXqP01sPJcKL6CoCBWg5IbMH7IRsA3lA63oYZsl1i0mqjfVUW/a+pn0plRVd7hnVGbHtjNqINC/KFUFaG6sL/ygTvagVolsqrW+WhqGYA0x3wfggdpOCjPMwPX7bj0t817d/dQpfW7YdB+f4AkX3PEluXiY/Dcstka/lO1F9ONYR0Zpmd53qGKt6IhwZeKHgCmrAw36/+NhUbZXcz3G32ns3+ULZtjhFbezgj1d3Nd5DYGWnyuBTWkXZKW3onhdb5mWwe/R62twfgds=
